version: 0.2

phases:
  install:
    runtime-versions:
      # Changed from 22 to 16. Node.js 16 is an LTS version and generally
      # compatible with older Create React App projects which might encounter
      # issues with newer Node.js versions and module resolution.
      nodejs: 16
    commands:
      - echo "--- Entering INSTALL phase ---"
      - pwd # Print current working directory
      - ls -l . # List contents of the current directory
      - echo "Navigating to frontend for install and installing dependencies..."
      - cd frontend && npm install
      - pwd
      - ls -l .

  build:
    commands:
      - echo "--- Entering BUILD phase ---"
      - pwd
      - ls -l .
      - echo "--- Building the React application ---"
      - npm run build
      - echo "--- Listing contents of build directory AFTER build ---"
      # These commands will only work if the 'build' directory is created.
      # They are kept for illustrative purposes to check build output.
      - ls -l build/
      - ls -l build/static/js/
      - ls -l build/static/css/

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build # This should be the directory containing the build output (e.g., 'build' folder for Create React App)
