version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Navigating to frontend and installing dependencies..."
      - cd frontend && npm install # Ensure npm install runs in frontend

  build:
    commands:
      - echo "--- Listing contents of frontend directory BEFORE build ---"
      - ls -l frontend/
      - ls -l frontend/src/
      - echo "--- Building the React application ---"
      - cd frontend && npm run build # Ensure npm run build runs in frontend
      - echo "--- Listing contents of build directory AFTER build ---"
      - ls -l frontend/build/
      - ls -l frontend/build/static/js/
      - ls -l frontend/build/static/css/ # Also check CSS files

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
