version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "--- Entering INSTALL phase ---"
      - pwd # Print current working directory
      - ls -l . # List contents of the current directory
      - echo "Navigating to frontend for install and installing dependencies..."
      - cd frontend && npm install # This changes the directory for subsequent commands in this phase
      - pwd # This will show /codebuild/output/src.../src/frontend
      - ls -l . # This will show contents of frontend directory

  build:
    commands:
      - echo "--- Entering BUILD phase ---"
      - pwd # Print current working directory (should be /codebuild/output/src.../src/frontend)
      - ls -l . # List contents of the current directory (should be contents of frontend)
      - echo "--- Building the React application ---"
      - npm run build # Now npm run build will execute in the frontend directory
      - echo "--- Listing contents of build directory AFTER build ---"
      - ls -l build/ # This is now relative to frontend/
      - ls -l build/static/js/
      - ls -l build/static/css/

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build # This path is relative to CODEBUILD_SRC_DIR
