version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Navigating to frontend for install and installing dependencies..."
      - cd frontend && npm install # Ensure npm install runs in frontend

  build:
    commands:
      - echo "--- Entering frontend directory for build phase ---"
      - cd frontend # Change to frontend directory for the rest of this phase
      - echo "--- Listing contents of current directory (frontend) BEFORE build ---"
      - ls -l .
      - ls -l src/ # List content of src/ relative to frontend
      - echo "--- Building the React application ---"
      - npm run build # Now 'npm run build' runs directly in 'frontend'
      - echo "--- Listing contents of build directory AFTER build ---"
      - ls -l build/
      - ls -l build/static/js/
      - ls -l build/static/css/

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
