version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies from the root directory..."
      - npm install # Install dependencies directly in the repository root

  build:
    commands:
      - echo "--- Listing root directory contents BEFORE build ---"
      - ls -l . # List contents of the repository root
      - ls -l src/ # List contents of the src/ folder
      - echo "--- Building the React application from the root ---"
      - npm run build # Now 'npm run build' runs directly in the repository root
      - echo "--- Listing contents of build directory AFTER build ---"
      - ls -l build/
      - ls -l build/static/js/
      - ls -l build/static/css/

artifacts:
  files:
    - '**/*'
  base-directory: build # The 'build' folder will be created directly in the root, not inside 'frontend/'
